# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd563b9b0533085dbfc60ca35aad33c56cf8ce43be2b7356a7018c440faf990f8fdfbb18a9db68658373fe9d4fa50648320e55006a57d0d7072b9eff9f18d0a2

test:
  secret_key_base: 0002116c17f895839c986e4aad31357338993fe5090f8a4cba40ede13f9ff27e9797f1e80f51126bb1040aefa20c44b903ca0d7d9cf44d63b847e4e8a220efa0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
